### ISSUE TITLE
Better images for sources

### ISSUE THREAD

**Issue by stefanprobst** [stefanprobst/dariah-campus-mdx#11]
Would be good to find better images for https://dariah-campus.netlify.com/sources

**Comment by ttasovac** [comment]
Agreed. 

However, I think we need to change the way sources are previewed in the categories template. It's very hard to get the image right with the dimensions currently used in for `<CategoryPreview>`. Also, as we realized yesterday, the number of sources will grow, so it's important that we can present them nicely and that we can fit more than two in a row.

So here's what I propose:

- let's make the new `<CategoryPreview>`  part of a responsive masonry layout (three columns for wide, two for tablet, and one for mobile view) similar to `PostPreview`
- let's add `data.category.previewImage` to the data model and place it in  `<CategoryPreview>` above the title and the description similar to
 this:  
    <img width="360" alt="Скриншот 2019-08-10 13 54 29" src="https://user-images.githubusercontent.com/5304839/62821518-77165c80-bb76-11e9-8419-bceded523609.png"> 
    but with rounded corners as in `<PostPreview>` (the image will be effectively rounded only at the top, but not at the bottom... I hope that will look ok, let's see). 
- let's try to add a footer, similar to `<PostPreview>`, to the new `<CategoryPreview>` with Read more on the right, and the number of resources on the left (please change "x Posts" to "x Resources" 
- finally, in the individual category template, let's add an optional banner image below `<LeadIn>`. It should be rendered only if `data.category.bannerImage` exists. 

`previewImage` and `bannerImage` should be two different objects. The banner will most likely have to have different dimensions than the preview image, so that it looks nice on the page. 

And then let's see how the whole thing looks.
