### ISSUE TITLE
Language metadata field

### ISSUE THREAD

**Issue by DeborahThorpe** [stefanprobst/dariah-campus-mdx#12]
Hi Stefan,

We were wondering if you implemented the language metadata field? Is English the default now?

Debs

**Comment by stefanprobst** [comment]
yes, for resources there is now a `lang` frontmatter field defaulting to `en`:
https://github.com/stefanprobst/dariah-campus-mdx/blob/9abe75ccc972477ad90153e4c6729a7724f89e05/gatsby-node.js#L189

**Comment by DeborahThorpe** [comment]
Hi @stefanprobst @ttasovac 
Reopening this to ask a question: 
Several of the #dariahTeach courses are available in multiple languages.
For example:
Spacial Image Analytics:
English
https://teach.dariah.eu/course/view.php?id=29
Greek
https://teach.dariah.eu/course/view.php?id=42

Both languages are accessible from the default English page (see links at top of page), so shall we just create one entry with multiple languages listed (ie. "lang: en gr")? Or shall we create separate entries for each language?

**Comment by stefanprobst** [comment]
i think that's something you have to decide. currently the `lang` field is a scalar, i.e. it accepts only a single value

**Comment by ttasovac** [comment]
i'd prefer it that we don't add non-english content yet. it won't look good because there will be very few resources in langauges other than english, just a handful from dariahTeach, so d-c wouldn't be a very useful resource for non-english speakers.

multilingual content is something for us to discuss post-november... how to solicit more of it, how to integrate it, how to search it etc. etc. 
--
Belgrade Center for Digital Humanities
http://humanistika.org
